### ISSUE TITLE
Query regarding bug bounty

### ISSUE THREAD

**Issue by bug-vs-me** [vesoft-inc/nebula-dashboard#215]
want to ask do you have any bug bounty program or do your team provide bounty for reporting critical issues? because i found 1 critical issue

Thank you

**Comment by QingZ11** [comment]
Hi @deepak9876, we don't have a bounty for reporting bugs. We are welcome you to report bug, and then we will fix it soon.

**Comment by deepak9876** [comment]
@QingZ11 its not a bug but a vulnerability can't report it publically!

its critical issue!
