### ISSUE TITLE
Can you help me check the num_heartbeats is right? 

### ISSUE THREAD

**Issue by qilaijun101** [vesoft-inc/nebula-dashboard#247]
I can not confirm the  num_heartbeats is right, please help me check it .

There are 3 meta nodes, but only one can get num_heartbeats.
![image](https://user-images.githubusercontent.com/14890813/233964535-93fd860d-db83-4bb0-9981-e43f90f8fff1.png)

**Comment by qilaijun101** [comment]
![image](https://user-images.githubusercontent.com/14890813/233966284-e871518f-e206-47d4-bb91-027ddbaa9f2d.png)
at the same time ,the num_active_sessions of graphd  has the value of -1???

**Comment by xigongdaEricyang** [comment]
check the config in grahd.conf and storaged.conf, if the  value of config key `meta_ meta_server_addrs ` contains all meta address ?

![image](https://user-images.githubusercontent.com/9858560/236396939-b50ad5a2-790d-468f-93d9-fce20bf255a5.png)

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

这个 issue 超过一个月没有更新内容了，这边先行关闭了。如果你有任何更新的内容，可以再打开这个 issue 哈。

谢谢你的反馈 😊
