### ISSUE TITLE
find some bugs in master branch

### ISSUE THREAD

**Issue by lwhere** [vesoft-inc/nebula-dashboard#49]
1:
<img width="985" alt="9d790adac97a1fc1bd0876316bcb52c" src="https://user-images.githubusercontent.com/34545964/170211436-e214673d-4cd6-466a-98fe-1b7c316c9781.png">
Here, "@base" is not defined, should be "@/" instead
2:

![image](https://user-images.githubusercontent.com/34545964/170211851-f145bd45-b030-46fb-bcaf-b837698cb345.png)
There should be another ")" here.
3: (not fixed yet)
![image](https://user-images.githubusercontent.com/34545964/170212029-6ef537bc-928a-4d2b-bebb-c15a56ca8dd8.png)
However, when I have fixed above two little bugs which the webpack indicates directly , I still cann't "npm run dev" the project, 
it told me that "ERROR in Conflict: Multiple assets emit different content to the same filename index.html".
4: (not fixed yet)
I first try to use pnpm to install the node_modules, but it turns out "it can't find some modules". I try yarn latter and find out that "can't find modules" problem disappears.

**My Environments**

* OS: Windows & Linux
* Node-version: node: 16.15.0
* Dashboard-version: master

**Comment by xigongdaEricyang** [comment]
fixed it  already, thanx a lot
