### ISSUE TITLE
How to get the disk monitor data

### ISSUE THREAD

**Issue by SevenLM361** [vesoft-inc/nebula-dashboard#99]
How to get the disk monitor data in your code，i want to add some features in the dashboard.

![image](https://user-images.githubusercontent.com/42933171/178518719-04efd42f-b4ce-4067-9861-191840c482a0.png)

**Comment by xigongdaEricyang** [comment]
You can read  code in this file [DiskCard](https://github.com/vesoft-inc/nebula-dashboard/blob/master/src/pages/MachineDashboard/Cards/DiskCard.tsx)

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
